# Generated by Django 5.2.5 on 2025-08-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_category_tag_business_category_business_tags_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-stars']},
        ),
    ]
